version: '3.7'

services:
  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: ayebraine/foodgram-frontend:latest
    depends_on:
      - db
    volumes:
      - ./frontend/:/app/result_build/

  web:
    image: ayebraine/foodgram-backend:latest
    restart: always
    ports:
      - 8001:8000
    depends_on:
      - frontend
    links:
      - frontend
    env_file:
      - .env
    volumes:
      - static:/app/backend_static/
      - media:/app/backend_media/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/html/api/docs/
      - ./frontend/build:/usr/share/nginx/html/
      - static:/var/html/backend_static/
      - media:/var/html/backend_media/
    depends_on:
      - web
      - frontend

volumes:
  postgres_data:
  static:
  media:
