version: '3.7'

services:
  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: ayebraine/foodgram-backend:latest
    volumes:
      - static:/app/static/
      - media:/app/media/
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    depends_on:
      - web
    links:
      - web
    volumes:
      - ../frontend/:/app/result_build/
      - static:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
      - ../frontend/build:/usr/share/nginx/html
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media:
