# Generated by Django 3.2.16 on 2022-11-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221105_1511'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reciingredi',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
        migrations.AlterModelTable(
            name='reciingredi',
            table='recipes_recipe_ingredient',
        ),
    ]
